# AeroSpace configuration
# https://nikitabobko.github.io/AeroSpace/guide

# Start AeroSpace at login
start-at-login = true

# Normalize windows on startup
on-focused-monitor-changed = ['move-node-to-monitor focused']

# Mouse follows focus
[mode.main.binding]
# Disable default alt+letter workspace switching
alt-f = 'nop'

# Window focus navigation
cmd-alt-h = 'focus left'
cmd-alt-j = 'focus down'
cmd-alt-k = 'focus up'
cmd-alt-l = 'focus right'

# Window movement
cmd-alt-shift-h = 'move left'
cmd-alt-shift-j = 'move down'
cmd-alt-shift-k = 'move up'
cmd-alt-shift-l = 'move right'

# Window resizing
cmd-alt-shift-u = 'resize smart -50'
cmd-alt-shift-i = 'resize smart +50'

# Window joining
cmd-alt-shift-y = 'join-with right'
cmd-alt-shift-o = 'join-with down'

# Layout management
cmd-alt-shift-n = 'layout floating tiling'
cmd-alt-shift-m = 'layout tiles'

# Focus management
cmd-alt-shift-p = 'focus-back-and-forth'

# Default layouts
[[workspace]]
name = '1'
layout = 'tiles'

[[workspace]]
name = '2'
layout = 'tiles'

[[workspace]]
name = '3'
layout = 'tiles'

[[workspace]]
name = '4'
layout = 'tiles'

# Gaps configuration
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10