# Default layout configuration for 2x2 grid
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

[mode.main.binding]

# focus navigation around tree (frequent operations)
cmd-opt-h = "focus left"
cmd-opt-j = "focus down"
cmd-opt-k = "focus up"
cmd-opt-l = "focus right"

# move the focused window within layout (frequent operations)
cmd-opt-shift-h = "move left"
cmd-opt-shift-j = "move down"
cmd-opt-shift-k = "move up"
cmd-opt-shift-l = "move right"

# window resizing (right-hand keys)
cmd-opt-shift-u = "resize smart -50"
cmd-opt-shift-i = "resize smart +50"

# window splits (right-hand keys)
cmd-opt-shift-y = "join-with right" # vertical side by side
cmd-opt-shift-o = "join-with down"  # horizontal stacked

# layout management (right-hand keys)
cmd-opt-shift-n = "layout floating tiling"
cmd-opt-shift-m = "layout tiles"

# focus back-and-forth (right-hand keys)
cmd-opt-shift-p = "focus-back-and-forth"

